name: Deploy Theme

on:
  push:
    branches:
      - prod  # деплой только при пуше в prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./
          server-dir: /domains/lonemagnet.com/public_html/wp-content/themes/lone-magnet/
          exclude: |
            lone-magnet/node_modules/
            lone-magnet/.git/
            lone-magnet/.github/
            lone-magnet/tcpdf/
          dangerous-clean-slate: true
