name: Deploy WordPress Theme to Hostinger

on:
  push:
    branches:
      - prod  # деплой только при пуше в prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # если нужно, иначе можно убрать

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./ 
          server-dir: /domains/lonemagnet.com/public_html/wp-content/themes/lone-magnet/
          exclude: |
            node_modules
            .git*
            .github
            package-lock.json
            package.json
